import Head from 'next/head';
import HomeTitle from 'src/sections/HomePage/HomeTitle';
import { PageContainer, SpinnerCSS } from '../../styles/PageLayout/PageContainer.css';

import RouterExample from 'src/sections/HomePage/RouterExample';
import JestExamples from 'src/sections/JestExample/JestExamples';

const Spinner = () => {
  return <div className={SpinnerCSS}>LOADING YOU FOOL!</div>;
};

const Home = () => {
  return (
    <>
      <Head>
        <title>Project Starter</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={PageContainer}>
        <HomeTitle title="Main Title" />

        <h1>Project Starter</h1>
        <ul>
          <li>Next 13 with SWC</li>
          <li>TypeScript</li>
          <li>Jest</li>
          <li>Vanilla Extract CSS</li>
        </ul>

        <Spinner />

        <RouterExample />
        <JestExamples />
      </main>
    </>
  );
};
export default Home;
