import Head from 'next/head';
import HomeTitle from 'src/sections/HomePage/HomeTitle';
import JestExamples from 'src/sections/JestExample/JestExamples';
import { PageContainer } from '../../styles/appStyles.css';

const xx = 'fish cakes';

const dog = 'bark';

const things = ['aya', 'doooood!!!', 'candy', 'uniconrn', 'aadsfaf', 'chocko', 'aadsfaf', 'candy', 'candy', 'uniconrn'];

const obj = {
  name: 'candy',
  dog: 'poopy',
  job: 3,
};

const Home = () => (
  <div className={PageContainer}>
    <Head>
      <title>Project Starter</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <HomeTitle title="Main Title" />

      <h1>Project Starter</h1>
      <h6>Packages</h6>
      <ul>
        <li>TypeScript</li>
        <li>Jest</li>
        <li>Vanilla JS</li>
      </ul>

      <JestExamples />
    </main>
  </div>
);
export default Home;
