import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import JestExamples from '../sections/JestExample/JestExamples'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Project Starter</h1>
        <h6>Packages</h6>
        <ul>
          <li>TypeScript</li>
          <li>Jest</li>
          <li>Vanilla JS</li>
        </ul>

        <JestExamples />
      </main>

      
    </div>
  )
}

export default Home
